services:

  backend:
    build:
      context: ./backend
    container_name: projeto-4-backend
    ports:
      - "5000:3004"
    env_file:
      - ./backend/.env
    networks:
      - cin_proxy
    restart: unless-stopped

  frontend:
    build:
      context: ./Front
    container_name: projeto-4-frontend
    volumes:
      - /opt/docker/frontends/projeto4:/output
    depends_on:
      - backend
    restart: "no"
    networks:
      - cin_proxy

networks:
  cin_proxy:
    external: true