events {}

http {
    server {
        listen 80;

        # Rota para a API (Backend)
        # Quando acessar clinicasdigitais.../NPI/api, joga para o backend na porta 5000
        location /NPI/api/ {
            proxy_pass http://backend:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Rota para o Frontend 
        # Qualquer outra coisa dentro de /NPI cai no frontend na porta 5173
        location /NPI/ {
            proxy_pass http://frontend:5173/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Suporte a WebSockets, Necessário para o Hot Reload do Vite
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}