# Usa a mesma imagem do Node
FROM node:22-alpine

# Define a pasta de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia dependências e instala
COPY package.json ./

RUN npm install

# Copia o restante do código React
COPY . .

# Expõe a porta 5173 do Vite
EXPOSE 5173

# Roda o Vite expondo para a rede do Docker 
CMD ["npm", "run", "dev", "--", "--host"]